### ISSUE TITLE
SEO Forum click here link should be seo_forum_meta_description not forum_meta_description

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2311] opened 2018-07-06 20:19 UTC
----------------------------------------

## What happened?
...click here link not correct format like the rest of SEO click here links

## Steps to reproduce:
1. admincp
2. settings
3. seo >> find forum description and forum keywords click here links not correct

## What is expected?

- this is what we have now for Meta Description: 

`<title>Forum Meta Description</title><info>Meta description added to pages related to the Forum app. <a target="_bank" href="https://www.yourdomain.com/index.php/admincp/language/phrase/?q=forum_meta_description">Click here</a> to edit meta description.<span style="float:right;">(SEO) <input style="width:150px;" readonly value="forum_meta_description"></span></info>`

**- Forum Meta Description should be this below:**

`<title>Forum Meta Description</title><info>Meta description added to pages related to the Forum app. <a role="button" onclick="$Core.editMeta('seo_forum_meta_description', true)">Click here</a> to edit meta description.<span style="float:right;">(SEO) <input style="width:150px;" readonly value="seo_forum_meta_description"></span></info>`

- this is what we have now for meta keywords :

`<title>Forum Meta Keywords</title><info>Meta keywords that will be displayed on sections related to the Forum app. <a target="_bank" href="https://www.yourdomain.com/index.php/admincp/language/phrase/?q=forum_meta_keywords">Click here</a> to edit meta keywords.<span style="float:right;">(SEO) <input style="width:150px;" readonly value="forum_meta_keywords"></span></info>`

**- Forum Meta Keywords should be this below:** 

`<title>Forum Meta Keywords</title><info>Meta keywords that will be displayed on sections related to the Forum app. <a role="button" onclick="$Core.editMeta('seo_forum_meta_keywords', true)">Click here</a> to edit meta keywords.<span style="float:right;">(SEO) <input style="width:150px;" readonly value="seo_forum_meta_keywords"></span></info>`

Thanks Spiro

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...

## Screenshots
...

**Comment by neil96** [comment] 2018-07-09 02:40
Duplicate of #2315

**Closed as completed by neil96** 2018-07-09 02:40 UTC
Labels: Duplicate
