### ISSUE TITLE
can't upload blogs, events, discussions, Photos, music or videos after creating a page when viewing with android phone htc

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2149] opened 2018-01-15 19:37 UTC
version 4.6.0 using - Firefox and chrome browser on android
tried wide-view on phone and portrait same thing, doesn't give you the little popup to select share songs or add an album or share a video or share photos  events, blogs, discussions (green plus sign) 
can't upload music 
or 
videos 
on a page with android phone htc
seems the plus button doesn't open anything

**Comment by neil96** [comment] 2018-01-17 03:22
Hi @spirogg , Could you give us more information.

Thanks!

**Comment by spirogg** [comment] 2018-01-17 03:48
Hi when I'm viewing my website on my phone. And I am on my profile I select profile photos and then try to add a photo using the green little circle with a plus sign. I cannot get it to work. The share photo doesn't show.

**Comment by spirogg** [comment] 2018-01-17 03:49
@neil96 same for videos, music, etc etc.  If I use the menu it works. But not under my  profile or page I created.

**Comment by spirogg** [comment] 2018-01-17 04:02
![phpfox-green-plus-button-doesnt-work](https://user-images.githubusercontent.com/17736688/35025100-fd61dc9a-fb08-11e7-99b2-b821ea76dcd4.png)
@neil96 here is photo of what im taking about, i click on my profile the select photo music etc etc and try to click on the green plus button that suppose to give you a little share photos etc etc doesnt work
![phpfox-photo-cant-upload](https://user-images.githubusercontent.com/17736688/35025098-fa5cc15e-fb08-11e7-965c-81f9fdf12ad3.png)

**Comment by spirogg** [comment] 2018-01-17 04:05
@neil96 also when i created a page, i try to select to add photo music and it doesn't work also cant upload cause the share popup doesn't show, pressing the green plus button doesn't do anything ?

**Comment by spirogg** [comment] 2018-01-17 04:10
![green-plus-button-doesnt do anything](https://user-images.githubusercontent.com/17736688/35025262-1db137ba-fb0a-11e7-931d-678b7a2f4980.png)

**Comment by spirogg** [comment] 2018-01-17 04:12
plus button that is top right that button doesn't do anything when viewing with chrome browser on my android phone 7.1.1 HTC phone

**Comment by spirogg** [comment] 2018-01-17 04:43
@neil96 this (Share Photos - doesn't show up on my cell phone when i click the green button

![share photos](https://user-images.githubusercontent.com/17736688/35026110-a6ef8a28-fb0e-11e7-8060-8afb06244809.jpg)

**Comment by spirogg** [comment] 2018-01-17 05:24
@neil96 when selecting the main menu to see all photos on site or all music on site the popup works to add photo and music, videos etc, 

![using main menu selecting music](https://user-images.githubusercontent.com/17736688/35027072-1fe6abe6-fb14-11e7-9428-b1a499659a49.png)

![selecting main menu photos](https://user-images.githubusercontent.com/17736688/35027085-3117f168-fb14-11e7-8e22-c7e22432bb67.png)



**@neil96 but when selecting from drop-down from groups pages your own profile it doesn't work**

**Comment by spirogg** [comment] 2018-01-17 05:27
@neil96 when selecting the main menu the Green + button doesn't move, it is on the bottom right as if it were floating and stays there as you scroll up or down, but on the other pages i show it moves when you scroll, so I think its got something to do with CSS or something in the placement of the button in the code

**Comment by spirogg** [comment] 2018-01-17 07:51
Sorry again in this post if I tagged you so much, from now on i'll only tag you once in each post 👍

**Comment by neil96** [comment] 2018-01-18 10:28
Duplicate of #2157

**Closed by neil96** 2018-01-18 10:28 UTC
Labels: Cannot reproduce
