### ISSUE TITLE
4.8.10 getting 500 error on the FORUM module when PAGES is turned on.

### ISSUE THREAD

**Issue by PhpFoxJohnJr** [PHPfox-Official/phpfox-v4-issues#3038] opened 2022-07-09 02:45 UTC
# Important

Please follow this template!

----------------------------------------

## What's happened?
After I upgraded to 4.8.10 I found out that if you have PAGES turned on then you get a 500 error when you attempt the FORUM module.
## Steps to reproduce:
1. 500 Forum Error occurs when PAGES and FORUM are turned ON.
2. I shut off PAGES and the FORUM does work.
3. This is the error I get.
Calling a Service from an invalid Module. Make sure the module is valid or set to active. (pages::pages) (/var/www/vhosts/mydomain.com/httpdocs/PF.Base/include/library/phpfox/error/error.class.php) [96]
Error Code: acf09e

See the thread that shows Steve is also having the same issue as well.
 
https://community.phpfox.com/forum/thread/58776/can-someone-check-this-out-for-me-to-make-sure-whether-it-is-a-real-bug-or-/

**Comment by harrison05** [comment] 2022-08-22 08:31
Duplicate of #3035

This is a bug in the Forums app, it will be fixed in the next version of Forums (v4.6.7). If you need a hotfix, please get in touch with us.

Regards.

**Closed as completed** 2023-06-08 02:52 UTC
Labels: Duplicate, Fixed
