### ISSUE TITLE
music SEO also show session ID see fix

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2313] opened 2018-07-06 20:53 UTC
----------------------------------------

## What happened?

 - music seo links: 

`<title>Music Meta Description</title><info>Meta description added to pages related to the Music app. <a target="_bank" href="admincp/language/phrase/?sessionid=5b3c5a4bc6f28?q=seo_music_meta_description">Click here</a> to edit meta description.<span style="float:right;">(SEO) <input style="width:150px;" readonly value="seo_music_meta_description"></span></info>`

**- should be:**

`<title>Music Meta Description</title><info>Meta description added to pages related to the Music app. <a role="button" onclick="$Core.editMeta('seo_music_meta_description', true)">Click here</a> to edit meta description.<span style="float:right;">(SEO) <input style="width:150px;" readonly value="seo_music_meta_description"></span></info>`

also keywords:
`<title>Music Meta Keywords</title><info>Meta keywords that will be displayed on sections related to the Music app. <a target="_bank" href="admincp/language/phrase/?sessionid=5b3c5a4bc6f28?q=seo_music_meta_keywords">Click here</a> to edit meta keywords.<span style="float:right;">(SEO) <input style="width:150px;" readonly value="seo_music_meta_keywords"></span></info>`

**- should be:**

`<title>Music Meta Keywords</title><info>Meta keywords that will be displayed on sections related to the Music app. <a role="button" onclick="$Core.editMeta('seo_music_meta_keywords', true)">Click here</a> to edit meta keywords.<span style="float:right;">(SEO) <input style="width:150px;" readonly value="seo_music_meta_keywords"></span></info>`

## Steps to reproduce:
1. admincp
2. settings
3. SEO >> music description and keyword click here links

Thanks Spiro

## What is expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...

## Screenshots
...

**Comment by spirogg** [comment] 2018-07-06 20:55
@neil96 please read this one again also: there is missing phrases so not working #2307

**Comment by neil96** [comment] 2018-07-09 02:39
Duplicate of #2315

**Closed as completed by neil96** 2018-07-09 02:39 UTC
Labels: Duplicate
