### ISSUE TITLE
When no stats are available for today, please hide the "Today" header in the site statistics block

### ISSUE THREAD

**Issue by hamadax** [PHPfox-Official/phpfox-v4-issues#2755] opened 2019-08-22 05:03 UTC
# Important

Please follow this template!

----------------------------------------

## What's happened?
When no stats are available for today, please hide the "Today" header in the site statistics block. It shows Today and nothing under it. Just hide the header as well in that case.

## Steps to reproduce:
1. You need a test installation where no activity happened today.
2. Check the Site Stats block.
3. It shows Today as a header with nothing under it.

## What's expected?
Just hide it or put a phrase under it saying "No activity today"

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

4.7.7

## Screenshots
...
![image](https://user-images.githubusercontent.com/48427415/63487287-9a93ae00-c478-11e9-8cb0-a668f723baa2.png)

I crossed out the line where it says 1 photo. It was not there prior. Just an empty area.

**Comment by harrison05** [comment] 2019-08-23 02:54
Which version of phpFox you're using? Because we fixed it. And I check with version 4.7.7, it doesn't appear
![Screen Shot 2019-08-23 at 09 47 04](https://user-images.githubusercontent.com/41947198/63563584-bb98f380-c58b-11e9-84cb-63af7f13ea8e.png)

**Comment by hamadax** [comment] 2019-08-23 03:22
4.7.7

![image](https://user-images.githubusercontent.com/48427415/63564535-68935200-c533-11e9-8de3-2bb1edd7ceda.png)

You are looking at All Time which will always have data. I am talking about Today's stats, which in my case does not show anything, since I have not officially launched yet. If no data exist for Today, it should be hidden. No point showing nothing!

**Comment by harrison05** [comment] 2019-08-26 02:33
Ok, after check carefully, I confirmed this is an issue. We will fix it.

Thanks

**Comment by david-phpFox** [comment] 2019-09-25 10:58
Fixed in Core 4.7.8.

**Closed as completed by david-phpFox** 2019-09-25 10:58 UTC
Labels: Bug, Core
