### ISSUE TITLE
Part of the username is sometimes displayed in two and three lines on his profile.

### ISSUE THREAD

**Issue by kerstar** [PHPfox-Official/phpfox-v4-issues#2550] opened 2019-01-14 02:51 UTC
## What's happened?
I translated phrases into other language and noticed an irritating problem. 
Namely, if the user has a long name, then part of the username is displayed in two lines on the user's profile, and sometimes even in three lines. I noticed that the problem does not occur in English, because there the "Add to Friends" button has 14 characters, including spaces, and the username is displayed on one line, while if the same button that I translated into another language has 24 characters with spaces, which results in the user's name being divided into two lines.
In case the username has 25 characters (default maximum value), the error even occurs in English - in this case the user's name is displayed in two lines, whereas in the case when the "Add to Friends" button is translated into another language, the username is displayed in three lines.

It's probably a issue, right?

Can You fix Harrison on my website? 
I have provided access to my website on the ticket number #790399. 
Thank you.

## Steps to reproduce:
1. Create a long username
2. In the default English language, the username will be displayed in two lines due to the fact that the "Add to Friends" button has 14 characters along with spaces.
3. If the "Add to Friends" button is translated into a different language, which will consist of a larger number of characters, the username will be displayed even in three lines

## Browsers and Devices tested
Chrome in Windows 10

## phpFox version
4.7.2

## Screenshots
![displayusername1](https://user-images.githubusercontent.com/38014237/51094720-af57e700-17af-11e9-8a6a-d1e4267d502e.png)
![displayusername2](https://user-images.githubusercontent.com/38014237/51094721-aff07d80-17af-11e9-967a-a91a366bd7c0.png)
![displayusername3](https://user-images.githubusercontent.com/38014237/51094722-aff07d80-17af-11e9-8a80-e281a3c47256.png)
![displayusername4](https://user-images.githubusercontent.com/38014237/51094723-aff07d80-17af-11e9-9821-8301e279d6e3.png)

**Comment by harrison05** [comment] 2019-01-14 03:45
I can't reproduce it on my site with version 4.7.2. So, we will check in your site via your submitted ticket.

Regards.

**Comment by kerstar** [comment] 2019-01-14 03:46
I understand. In that case, I am waiting for an answer. As additional information, let me say that my version 4.7.2 is a clean, new installation (not updated from the previous version).

**Comment by harrison05** [comment] 2019-01-15 03:16
Ok. Our support team will check and update status in your ticket.

Thanks.

**Comment by kerstar** [comment] 2019-01-17 06:05
Harrison, can you show a screen shot of how it looks on your page if the user has 25 characters in his name (default maximum value)? Paul has not dealt with my ticket yet, because I do not have paid support and I have a low priority, so I thought I would write here. Thanks.

**Comment by harrison05** [comment] 2019-01-18 03:13
In my site, everything is working well
![screen shot 2019-01-18 at 10 09 37](https://user-images.githubusercontent.com/41947198/51363128-3a671300-1b09-11e9-9dab-e61d5e775c9e.png)

Which version of Material Template on your site (4.7.2 is the newest version)? In my memory, we found a similar issue in the old version and fixed in the newest version of Material.

Regards.

**Comment by kerstar** [comment] 2019-01-18 03:17
Harrison, I have a phpfox version 4.7.2 (fresh installation, not upgraded from an earlier version).  I probably know where the problem is. The issue is caused by the "Follow" application button, which takes up space so that the username has less space for display.
I'm right? Can you confirm this?
I paste a screenshot of your demo page, where the user has 25 characters - displayed from another profile as a logged in user.
![displayusername5](https://user-images.githubusercontent.com/38014237/51363385-07585b80-1ad8-11e9-9a1f-f9a9faf07dad.png)

**Comment by harrison05** [comment] 2019-01-18 03:23
Do you mean **Follow System** App? 
If right, this is 3rd app and I think it makes error with your layout. You can try to disable this app > Rebuild core theme > Clear cache and test again.

**Comment by kerstar** [comment] 2019-01-18 03:31
Yes, I meant the Follow System App. 
Ok, I will check the way you wrote about it, but I will use this application. 
It seems that I will have to work around this problem somehow. 
Thanks for the advice.

**Comment by harrison05** [comment] 2019-01-18 03:36
You can request support from Follow App's owner to check and help you fix it.

Thanks.

**Closed as completed** 2019-01-20 02:53 UTC
Labels: Cannot reproduce
