### ISSUE TITLE
Posts in Shoutout box disappeared after refreshing page.

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-issues#2075] opened 2017-12-14 16:21 UTC
I installed 4.6 Beta and get an error showing below the post in the Shoutout box 
and when the page is refreshed all posts disappear.

![error-shown-in-shoutout-box](https://user-images.githubusercontent.com/17064302/34002308-28ba46b8-e0ea-11e7-8a9c-e8c74e483885.png)

![disappeared-in-shoutout-box](https://user-images.githubusercontent.com/17064302/34002547-c30b6f26-e0ea-11e7-9d59-10fc8d8a2c5a.png)

**Comment by neil96** [comment] 2017-12-15 02:29
Hi @starplan ,

The messages are not sent successfully. You can see the "**Error**" below the message. Please open the console log on your browser and copy the error here.

Thanks!

**Comment by starplan** [comment] 2017-12-15 12:59
[shoutbox error.zip](https://github.com/PHPfox-Official/phpfox-v4-issues/files/1562704/shoutbox.error.zip)

**Comment by neil96** [comment] 2017-12-26 01:22
Hi @starplan ,

I can't see any errors in your log. Some servers can't run if the php file has permission 777. We fixed in issue. It might be this is root cause.

Regards.

**Closed** 2018-01-02 09:44 UTC
