### ISSUE TITLE
Can not find some users in simple admin search by email or name

### ISSUE THREAD

**Issue by ChijiokeNN** [PHPfox-Official/phpfox-v4-issues#2064] opened 2017-12-06 01:12 UTC
unable to find some registered users in admin panel simple search by typing in either their name or email and clicking search without entering their city, state and country. Debug has been enabled on my server as instructed by Phpfox but the problem still persists

**Comment by neil96** [comment] 2017-12-06 01:57
Hi @ChijiokeNN ,

Could you give us more information.

Regards.

**Comment by ChijiokeNN** [comment] 2017-12-07 13:12
![screenshot 2017-12-07 07 05 01](https://user-images.githubusercontent.com/16528633/33716948-b27e99bc-db1d-11e7-8e88-b3d402592ab9.png)

![screenshot 2017-12-07 07 04 43](https://user-images.githubusercontent.com/16528633/33716895-7ccff16c-db1d-11e7-92bf-4d243926a592.png)

![screenshot 2017-12-07 07 04 09](https://user-images.githubusercontent.com/16528633/33716883-74ee8684-db1d-11e7-8afa-50c65f354fd4.png)

![screenshot 2017-12-07 07 03 35](https://user-images.githubusercontent.com/16528633/33716875-6df90e12-db1d-11e7-854e-facfdcf1f72c.png)

![screenshot 2017-12-07 07 03 11](https://user-images.githubusercontent.com/16528633/33716861-629b2db6-db1d-11e7-9d28-2bd8de01f717.png)

![screenshot 2017-12-07 07 02 49](https://user-images.githubusercontent.com/16528633/33716856-58e051e8-db1d-11e7-956f-4aa3be4d2acb.png)
Hello Neil, 
Here are some screenshots of what i am talking about
![screenshot 2017-12-07 07 02 08](https://user-images.githubusercontent.com/16528633/33716846-4d547d22-db1d-11e7-8067-d03a61db23b2.png)

**Comment by ChijiokeNN** [comment] 2017-12-07 13:27
When you go to admin> members>search> name> then type in Prince Dylan or use this email brandoniroc@gmail.com to search for same user. This user cannot be found in admin search like this as displayed in the screenshots above. Once you type in the name you are searching for or use their email to do the same search it pulls up nothing as you can see in the screenshots, but search for the same user in the open site you easily find him. It appears that this has been reported as a BUG by ScriptsTechDonna previously.

**Comment by ChijiokeNN** [comment] 2017-12-07 13:38
Hello Neil,

Like you can see on the screenshots admin>members>search>name>prince Dylan>search nothing shows up, do same using his email brandoniroc@gmail.com with same result.

Chijioke N

________________________________

**Comment by neil96** [comment] 2017-12-08 01:33
Hi @ChijiokeNN ,

How do you know that user exists on your system? It can cancel their account or is deleted by other admin.

Regards.

**Comment by ChijiokeNN** [comment] 2017-12-08 05:42
Hello,
I created that user myself for testing purposes when this issue was raised a colleague, so that account is still there and it's also found on the front of the site under members.
Chijioke

Sent from my iPhone

On Dec 7, 2017, at 7:33 PM, Neil J. <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @ChijiokeNN<https://github.com/chijiokenn> ,

How do you know that user exists on your system? It can cancel their account or is deleted by other admin.

Regards.

**Comment by neil96** [comment] 2017-12-11 04:33
Hi @ChijiokeNN ,

I created the user with the email and name above, but I still can't reproduce.

Regards.

**Comment by ChijiokeNN** [comment] 2017-12-19 13:41
They said it is bug, could you log into my site and try finding this user either with email or name. Could the bug be only on my script only, thought such would be script wide on all scripts by Fox.

Thanks,

Chijioke

________________________________

**Comment by neil96** [comment] 2017-12-19 15:05
Ok @ChijiokeNN ,

Please submit a ticket [here](https://clients.phpfox.com/submitticket.php) with your site information and attach the link of this issue. I will check on your site.

Regards.

**Comment by ChijiokeNN** [comment] 2017-12-21 15:34
Hello Neil J,

I have submitted this ticket below at phFox as you requested, here is a copy but without the login credentials here.


Hello Neil J,
I am submitting the ticket as a follow up to the issue i reported on GitHub which you are following up from GitHub.
Issue is we are unable to find some users searching for them on admin panel. EG: prince dylan with email brandoniroc@gmail.com could not be found there with either name or email on my site but he is there on open site side, i created this user for testing purposes.
My site is www.invincible.mobi
Credentials:
username:
password:
Not sure how to attach the link you mentioned in your email but below i have copied from your email:

You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

Warm Regards,
Chijioke



________________________________

**Comment by neil96** [comment] 2017-12-22 03:47
Hi @ChijiokeNN ,

This issue is reported and fixed in old phpFox version. Please upgrade your site to latest version.

Regards.

**Closed by neil96** 2017-12-22 03:47 UTC
Labels: Cannot reproduce, Duplicate

**Comment by ChijiokeNN** [comment] 2018-01-28 03:28
Hello Neil,

The previous problem seems to have been solved with the upgrade, but i have a new problem, my site is unable to send email, Cron Job has been enabled on my server and the Path setup but still i am unable to send out email. At the test email it shows sent but never gets to the recipient email, friends say it is a bug, could you help please.

Many thanks,

Chijioke

________________________________

**Comment by neil96** [comment] 2018-01-29 00:45
Hi @ChijiokeNN ,

For this case, please ask on our [community](https://community.phpfox.com/forum/) or submit a ticket [here](https://clients.phpfox.com/submitticket.php).

Regards.
