### ISSUE TITLE
Modified files after a fresh installation 4.6.1б5

### ISSUE THREAD

**Issue by kaligula7** [PHPfox-Official/phpfox-v4-issues#2364] opened 2018-08-20 21:14 UTC
# Important!

Please follow this template!

----------------------------------------

## What happened?
121 Modified files after a  fresh installation 4.6.1б5

## Steps to reproduce:
1. fresh installation
2. ACP - Maintenance - Check Modified Files (/index.php/admincp/checksum/modified/)
3. 121 Modified files

## What is expected?
...

## Browsers and Devices tested
 Windown 7, Firefox 

## Server information
Example: CentOS 7, php 7.2.8 apache FCGI

...

## phpFox version
 phpFox 4.6.1B5

...

## Screenshots
...

**Comment by spirogg** [comment] 2018-08-22 05:09
duplicate of #2198

**Closed as completed** 2018-08-22 06:37 UTC
Labels: Duplicate
