### ISSUE TITLE
Blog double posts

### ISSUE THREAD

**Issue by djafrika** [PHPfox-Official/phpfox-v4-issues#2567] opened 2019-01-23 13:23 UTC
What's happened?
When I click on blog tag, it displays all blogs with that tag but also doubles each blog. 

Steps to reproduce:
1. add blog with tags
2. click on tag
3. see double posts

What's expected?
Not to display same blog twice

Browsers and Devices tested
Chrome on Windows 10

Server information
CentOS 7, php 7.3 apache, nginx

phpFox version
4.7.2

**Comment by harrison05** [comment] 2019-01-24 04:04
Can't reproduce your issue, see my screenshot, it only shows one time. 
Your issue with tag or hashtag?
![screen shot 2019-01-24 at 11 01 30](https://user-images.githubusercontent.com/41947198/51653773-7b5a9e00-1fc7-11e9-8102-a5e2c5a70484.png)

![screen shot 2019-01-24 at 11 05 12](https://user-images.githubusercontent.com/41947198/51653874-f4f28c00-1fc7-11e9-8bd6-8f00bfe441e2.png)

**Comment by djafrika** [comment] 2019-01-24 11:40
Tags. Do you have any idea why it doubles posts?

**Comment by harrison05** [comment] 2019-01-25 03:22
Ok, I check again and found the way to reproduce it. 
This issue only occurs when you add a new Blog with Tags and Hashtag and both of them have the same value.
Ex: Hashtag is **#blog** and Tags is **blog**
Bug of Blog, we will check and fix.

Thanks.

**Comment by david-phpFox** [comment] 2019-04-26 04:02
Fixed in Blog 4.6.5

**Closed as completed by david-phpFox** 2019-04-26 04:02 UTC
Labels: Bug, Blog App
