### ISSUE TITLE
video meta description and keywords show session ID see fix

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2312] opened 2018-07-06 20:31 UTC
# Important!

Please follow this template!

----------------------------------------

## What happened?

`<title>Video Meta Description</title><info>Meta description added to pages related to the Video app. <a target="_bank" href="admincp/language/phrase/?sessionid=5b3c5a6235e43?q=seo_video_meta_description">Click here</a> to edit meta description.<span style="float:right;">(SEO) <input style="width:150px;" readonly value="seo_video_meta_description"></span></info>`

**- should be:**

`<title>Video Meta Description</title><info>Meta description added to pages related to the Video app. <a role="button" onclick="$Core.editMeta('seo_video_meta_description', true)">Click here</a> to edit meta description.<span style="float:right;">(SEO) <input style="width:150px;" readonly value="seo_video_meta_description"></span></info>`

**- also** 

`<title>Video Meta Keywords</title><info>Meta keywords that will be displayed on sections related to the Video app. <a target="_bank" href="admincp/language/phrase/?sessionid=5b3c5a6235e43?q=seo_video_meta_keywords">Click here</a> to edit meta keywords.<span style="float:right;">(SEO) <input style="width:150px;" readonly value="seo_video_meta_keywords"></span></info>`

**- should be:**

`<title>Video Meta Keywords</title><info>Meta keywords that will be displayed on sections related to the Video app. <a role="button" onclick="$Core.editMeta('seo_video_meta_keywords', true)">Click here</a> to edit meta keywords.<span style="float:right;">(SEO) <input style="width:150px;" readonly value="seo_video_meta_keywords"></span></info>`

thanks spiro

## Steps to reproduce:
1. admincp
2. settings
3. seo 

## What is expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...

## Screenshots
...

**Comment by neil96** [comment] 2018-07-09 02:40
Duplicate of #2315

**Closed as completed by neil96** 2018-07-09 02:40 UTC
Labels: Duplicate
