### ISSUE TITLE
v4.7 Does not retain size or position of pages avatar after upgrade

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2429] opened 2018-11-18 20:06 UTC
v4.7 Does not retain size or position of pages avatar after upgrade and switching from bootstrap to material theme

**Comment by harrison05** [comment] 2018-11-19 03:20
Could you give us more information?

Thanks!

**Comment by prepperz** [comment] 2018-11-19 04:06
Not all of the avatar on pages are displaying correctly after the upgrade. Some looks fine and some are not. 
![screenshot](https://user-images.githubusercontent.com/19594886/48685842-8ee02780-eb86-11e8-9133-06a40fafb663.png)

**Comment by harrison05** [comment] 2018-11-26 03:04
I can't reproduce it on my site. You can create a ticket, then we can check directly on your site.

**Comment by spirogg** [comment] 2018-11-28 08:25
See #2439 might help this issue also

**Comment by harrison05** [comment] 2018-12-04 04:08
@prepperz We checked on your site with information from your ticket, this is a bug if your Page lost cache for avatar id in phpfox_cache table. We hotfix issue on your site, and will fix in Pages App.

Regards.

**Comment by david-phpFox** [comment] 2018-12-13 05:00
Fixed in Groups 4.7.0

**Closed as completed by david-phpFox** 2018-12-13 05:00 UTC
Labels: Bug, Fixed, Pages App
