### ISSUE TITLE
music_song is not a valid module. music_album is not a valid module

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2353] opened 2018-08-08 19:00 UTC
----------------------------------------

## What happened?
...     music_song is not a valid module.  music_album is not a valid module when in Manage Sponsorships you click on a song or album you sponsored and click on that link

## Steps to reproduce:
1. Manage Sponsorships
2. click on a link that is music and album that you sponsor
3. 

## What is expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...4.6.1.b5

## Screenshots
...

**Comment by spirogg** [comment] 2018-08-08 19:14
also when you click on a forum thread in Manage Sponsorships  sponsored ad it says the same thing

**Comment by spirogg** [comment] 2018-08-09 01:20
#2347

**Comment by harrison05** [comment] 2018-08-09 04:24
Duplicate of #2347

**Closed as completed** 2018-08-09 04:24 UTC
