### ISSUE TITLE
Delete videos from pages takes user away from page to main video

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2466] opened 2018-12-10 05:34 UTC
This has been reported for years and it quickly gets annoying after a while.

**Comment by harrison05** [comment] 2018-12-12 03:46
Do you check with the newest version? We can't reproduce on our side. After deleted video in page, it redirect to **pages/<page_id>/video/**

**Comment by prepperz** [comment] 2018-12-12 05:45
Steps to reproduce: goto pages video > click on gear of video > then select delete. 

It will take you to main video that is no longer on the page.

**Comment by harrison05** [comment] 2018-12-13 03:10
Finally, I can reproduce. It only occurs when you delete a Video in a Page and you aren't an Admin of this Page.

**Comment by david-phpFox** [comment] 2018-12-18 05:10
Will fix in Videos 4.7.1

**Comment by david-phpFox** [comment] 2018-12-20 03:23
Fixed in Videos 4.7.1

**Closed as completed** 2018-12-20 03:23 UTC
Labels: Bug, Fixed, Video App
