### ISSUE TITLE
@harrison05 please read again  SEO meta description and keywords  for groups app has no place to add keyword or description. Please fix this one. 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2307] opened 2018-07-04 23:17 UTC
@harrison05 this is a bug  ----------------------------------------

## What happened?
...
When I go to admincp find SEO and click on the links for meta description and keywords under groups there is no area for me to input - type in my meta description keywords etc. 
## Steps to reproduce:
1. Go to admincp select SEO then look for groups meta. Click the link(s) and you will see no area to input any text for meta description nor keywords. 
2. 
3. 

## What is expected?
... Should have input area to add your meta description and keywords. 

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
Chrome 
## Server information
(Example: CentOS 7, php 7.1 apache)

...centos 7 php7.1 apache

## phpFox version
(Example: phpFox 4.6.0)

...4.6.1.b4

## Screenshots
...

**Comment by neil96** [comment] 2018-07-06 02:46
Hi @spirogg ,

We support multi languages for this feature. When you `click here` link, it will redirect you to page edit phrase, and you can edit the SEO phrase there. 

<img width="827" alt="screen shot 2018-07-06 at 09 44 08" src="https://user-images.githubusercontent.com/15936115/42357283-5f0098aa-8101-11e8-89d5-f27eb3a3e690.png">


Regards.

**Comment by spirogg** [comment] 2018-07-06 02:53
@neil96 
When I click here link there is nothing there to change or add in the groups app SEO.

**Comment by spirogg** [comment] 2018-07-06 16:51
All other apps have SEO except group app

**Comment by spirogg** [comment] 2018-07-06 19:51
## this is what I find and when in SEO in admincp I click here link its nothing

<title>Groups Meta Description</title><info>Meta description added to groups related to the Groups app. <a role="button" onclick="$Core.editMeta('groups_meta_description', true)">Click here</a> to edit meta description.<span style="float:right;">(SEO) <input style="width:150px;" readonly value="groups_meta_description"></span></info>

- Should link be: setting_phrase_groups_setting_meta_descriptions

## ALso for keyword same issue click here link i get nothing

<title>Groups Meta Keywords</title><info>Meta keywords that will be displayed on sections related to the Groups app. <a role="button" onclick="$Core.editMeta('groups_meta_keywords', true)">Click here</a> to edit meta keywords.<span style="float:right;">(SEO) <input style="width:150px;" readonly value="groups_meta_keywords"></span></info>

- Should link be: setting_phrase_groups_setting_meta_keywords

**Comment by spirogg** [comment] 2018-07-06 20:43
##music seo link also

`<title>Music Meta Description</title><info>Meta description added to pages related to the Music app. <a target="_bank" href="admincp/language/phrase/?sessionid=5b3c5a4bc6f28?q=seo_music_meta_description">Click here</a> to edit meta description.<span style="float:right;">(SEO) <input style="width:150px;" readonly value="seo_music_meta_description"></span></info>`

**- should be:** 

`<title>Music Meta Description</title><info>Meta description added to pages related to the Music app. <a role="button" onclick="$Core.editMeta('seo_music_meta_description', true)">Click here</a> to edit meta description.<span style="float:right;">(SEO) <input style="width:150px;" readonly value="seo_music_meta_description"></span></info>`


- also keywords:
`<title>Music Meta Keywords</title><info>Meta keywords that will be displayed on sections related to the Music app. <a target="_bank" href="admincp/language/phrase/?sessionid=5b3c5a4bc6f28?q=seo_music_meta_keywords">Click here</a> to edit meta keywords.<span style="float:right;">(SEO) <input style="width:150px;" readonly value="seo_music_meta_keywords"></span></info>`



**- should be:** 

`<title>Music Meta Keywords</title><info>Meta keywords that will be displayed on sections related to the Music app. <a role="button" onclick="$Core.editMeta('seo_music_meta_keywords', true)">Click here</a> to edit meta keywords.<span style="float:right;">(SEO) <input style="width:150px;" readonly value="seo_music_meta_keywords"></span></info>`

**Comment by neil96** [comment] 2018-07-09 02:34
Duplicate of #2315 

Hi @spirogg , your phrases in your site might not up to date, could you try to find missing phrase and test again.

Regards.

**Comment by spirogg** [comment] 2018-07-09 08:52
@neil96 I try missing phrases. Rebuild core. Find missing settings ?? Nothing works. I have nothing for groups phrases.

**Comment by spirogg** [comment] 2018-07-09 10:21
Are you sure you update the phrases and added phrase to input for keyword and description for groups. ?? In download 4.6.1.b4 I am going to redownload and install again. But I don't think you guys update your download with fix for groups phrases. ??

**Comment by spirogg** [comment] 2018-07-09 10:50
I delete everything re download from clients area and upload install and still no phrase for groups no section to enter keywords or description.  i tried find new phrases - clear cache - rebuilt theme 

**tried everything nothing there....**

click here link and say no phrases. the only thing i see when search up meta_group is these 2 

- groups_setting_meta_description
- setting_phrase_groups_setting_meta_description


![group app seo](https://user-images.githubusercontent.com/17736688/42446470-fcf876ae-833b-11e8-9158-7559b4e65874.PNG)
![group app seo2](https://user-images.githubusercontent.com/17736688/42446471-fd064720-833b-11e8-9f9b-6a30800e6fb7.PNG)

**Comment by spirogg** [comment] 2018-07-10 00:50
Can I just create them. 

groups_meta_description
And 
groups_meta_keywords

If so what do I create as ? 
Thanks.

**Comment by spirogg** [comment] 2018-07-10 16:34
@neil96 You said: 
try to find missing phrase: I did but nothing. Still no SEO area to add description or keywords. In groups app. 

in your demo here is issue  we have no where to input title and nothing for groups_meta_description and groups_meta_keywords  see your code below
v4.phpfox.com 
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"; dir="ltr" lang="en">
<head>
<title>Social Networking Community</title>
<meta name="description" content="groups_meta_description" />
<meta name="robots" content="index,follow" />
<meta name="keywords" content="social networking, phpFox demo, groups_meta_keywords" />

```

- also see photo below there is no title for groups but all others have title

![groups has no desscription](https://user-images.githubusercontent.com/17736688/42525651-4fe26d68-8439-11e8-9bcb-697e3e10da12.PNG)

**Comment by spirogg** [comment] 2018-07-13 03:10
**ok this is bug**

**Comment by spirogg** [comment] 2018-07-17 07:33
please also look at this #2321 similar issue but for pages

**Comment by spirogg** [comment] 2018-08-03 20:56
@neil96 you still have this as working as Designed when it's obvious its not working ??? there is no area to add SEO description and Keywords please.

**Comment by spirogg** [comment] 2018-08-07 04:01
@neil96 you said this was bug also please dont forget about this one... this is not working please
there is no place to add keywords or description 
nothing to add 
![group app seo](https://user-images.githubusercontent.com/17736688/42446470-fcf876ae-833b-11e8-9158-7559b4e65874.PNG)

nothing to add
![group app seo2](https://user-images.githubusercontent.com/17736688/42446471-fd064720-833b-11e8-9f9b-6a30800e6fb7.PNG)

**Comment by spirogg** [comment] 2018-08-07 04:35
I'm using 4.6.1.b5 fresh install and still there is no area to add keyword or description for groups. :(

**Comment by spirogg** [comment] 2018-08-20 06:35
@neil96 @harrison05 this is a bug. But still marked working as designed.  

It doesn't have a spot to add any keywords or description can you please mark it as bug and please give us a fix. This is going on for ever now.  !!!! Please fix this issue.

**Comment by spirogg** [comment] 2018-08-21 08:21
@paulkellow confirmed this is your issue in my support ticket. Just fyi.

**Comment by spirogg** [comment] 2018-08-22 03:39
Dear Spiro,

I can confirm that this is an issue of Core script. In the meantime, you can add following phrases manually in AdminCP:
- "groups_meta_description" -> Description
- "groups_meta_keywords" -> Keyword

Should you have any other questions, feel free to let us know.

Regards,
Paul Kellow

Support Staff
www.phpFox.com
Start Your Social Network Today!

**Comment by spirogg** [comment] 2018-08-22 03:50
- Also in title it doesn't say Groups, like all others

- <title>Pages | Social Networking Community</title>

- <title>Photos | Social Networking Community</title>

- <title>Music | Social Networking Community</title>

- all have name in title except for groups

- <title>Social Networking Community</title>


please fix this too

https://user-images.githubusercontent.com/17736688/42525651-4fe26d68-8439-11e8-9bcb-697e3e10da12.PNG

**Comment by spirogg** [comment] 2018-08-31 07:24
@harrison05 
this seems to be fixed. 
Thanks you guys. :)

**Closed as completed** 2018-09-11 05:46 UTC
Labels: Working as Designed
