### ISSUE TITLE
http / https doesn't redirect properly

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2488] opened 2018-12-17 13:30 UTC
## What happened?
http to https does not redirect properly

## Steps to reproduce:
1. For example: https://www.xxx.com/index.php/aquaponics/
2. Now change it to this: http://www.xxx.com/index.php/aquaponics/
3. It redirects to this: https://www.xxx.com/index.php/profile/index/  (page not found)

## What is expected?
...

## Browsers and Devices tested
Chrome on Windown 10

## Server information
CentOS 7, php 7  apache

...

## phpFox version
(Example: phpFox 4.7.1)

...

## Screenshots

**Comment by harrison05** [comment] 2018-12-19 04:03
I can't reproduce on my site. I might relate to server configs on your site. Please check your RewriteRule in the .htaccess file.

**Comment by prepperz** [comment] 2018-12-19 04:34
Tried it with and without the .htaccess file / rewrite rules and made no difference.

**Comment by harrison05** [comment] 2018-12-21 03:17
Do you try with solution in this link? 
https://stackoverflow.com/questions/4083221/how-to-redirect-all-http-requests-to-https

**Comment by prepperz** [comment] 2018-12-21 04:52
@harrison05 Thanks for the link. I'll look into it further. 

I originally have a .htaccess, but wanted to try it without. So this would suggest that the phpfox is redirecting it, yes/no? 

So, if there are no .htaccess file for redirection, it would then suggest that the phpfox redirect is not working properly on long links somehow. This is what I'm thinking.

**Comment by harrison05** [comment] 2018-12-25 03:24
Does this solution work on your site? This issue is weird, I checked with some sites without .htaccess file but still can't reproduce it.

**Comment by prepperz** [comment] 2018-12-25 08:49
Ya that is weird. Anyhow I put the .htaccess file back on with the following which works fine.

RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

**Comment by harrison05** [comment] 2018-12-26 02:50
I'm glad it helped. I will close this topic, let me know if you have any questions.

Regards.

**Closed as completed by harrison05** 2018-12-26 02:50 UTC
Labels: Cannot reproduce
