### ISSUE TITLE
poll seo small fix see below

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2316] opened 2018-07-06 21:09 UTC
# Important!

Please follow this template!

----------------------------------------

## What happened?
...

`<title>Poll Meta Description</title><info>Meta description added to pages related to the Poll app. <a role="button" onclick="$Core.editMeta('seo_poll_meta_description', true)">Click here</a> to edit meta description.<span style="float:right;">(SEO) <input style="width:150px;" readonly value="poll_meta_description"></span></info>`

**- should be:**

`<title>Poll Meta Description</title><info>Meta description added to pages related to the Poll app. <a role="button" onclick="$Core.editMeta('seo_poll_meta_description', true)">Click here</a> to edit meta description.<span style="float:right;">(SEO) <input style="width:150px;" readonly value="seo_poll_meta_description"></span></info>`

and this one:

`<title>Poll Meta Keywords</title><info>Meta keywords that will be displayed on sections related to the Poll app. <a role="button" onclick="$Core.editMeta('seo_poll_meta_keywords', true)">Click here</a> to edit meta keywords.<span style="float:right;">(SEO) <input style="width:150px;" readonly value="poll_meta_keywords"></span></info>`

**- should be:**

`<title>Poll Meta Keywords</title><info>Meta keywords that will be displayed on sections related to the Poll app. <a role="button" onclick="$Core.editMeta('seo_poll_meta_keywords', true)">Click here</a> to edit meta keywords.<span style="float:right;">(SEO) <input style="width:150px;" readonly value="seo_poll_meta_keywords"></span></info>`

**# the only thing I find different than other apps is this phrase**

 **- poll_setting_meta_keywords instead of poll_meta_keywords ??** 

sorry but just try to make unify all the SEO links hope this helps you 

Thanks Spiro

## Steps to reproduce:
1. 
2. 
3. 

## What is expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...

## Screenshots
...

**Comment by neil96** [comment] 2018-07-09 02:41
Duplicate of #2315

**Closed as completed by neil96** 2018-07-09 02:41 UTC
Labels: Duplicate
