### ISSUE TITLE
Theme issue in phpFox 4.7.8

### ISSUE THREAD

**Issue by kerstar** [PHPfox-Official/phpfox-v4-issues#2807] opened 2019-10-11 23:25 UTC
## What's happened?
The issue is that the bottom horizontal scrolling slider appears, although there are no elements on the page that cause this.
The issue occurs in some cases, in other cases there is no issue.

The only change I made was to disable the google map module in the database by phpMyAdmin. I don't know if this is the cause of the problem.

## Steps to reproduce:
1. Go to the home page
2. Click the "Sign In" button.

![theme_with_issue_step1](https://user-images.githubusercontent.com/38014237/66689647-0aa9fd80-ec8c-11e9-9d3f-a360fba86ec4.png)

3. In the login window that appears, leave the fields empty and click the blue "Sign In" button.

![theme_with_issue_step2](https://user-images.githubusercontent.com/38014237/66689651-15649280-ec8c-11e9-85f2-9ddf298fccf7.png)

4. On the next page, where the information about the incorrect login / password will appear, enter the correct data and then log in.

![theme_with_issue_step3](https://user-images.githubusercontent.com/38014237/66689696-3f1db980-ec8c-11e9-9672-1f64c8b0e218.png)

5. Go to user profile.
6. The bottom horizontal page scroll slider appears.

![theme_with_issue_after_login](https://user-images.githubusercontent.com/38014237/66689718-5a88c480-ec8c-11e9-8296-397bfebd6a30.png)

## What's expected?
The bottom slider for horizontal page scrolling appears

## Browsers and Devices tested
Google Chrome, Firefox

## phpFox version
PhpFox 4.7.8 (fresh installation)

## Screenshots

If you enter the correct details on the login page, there is no issue.

![theme_no_issue2](https://user-images.githubusercontent.com/38014237/66689757-87d57280-ec8c-11e9-825e-4b4d32cb8bd9.png)
![theme_no_issue1](https://user-images.githubusercontent.com/38014237/66689770-9d4a9c80-ec8c-11e9-859a-53c17d4e022e.png)

What's interesting is the difference in page code between normal logging in to the page and the case when we follow these steps:

1. Go to the home page
2. Click the "Sign In" button.
3. In the login window that appears, leave the fields empty and click the blue "Sign In" button.
4. On the next page, where the information about the incorrect login / password will appear, enter the correct data and then log in.
5. Go to user profile.
6. The bottom horizontal page scroll slider appears.

![theme_issue_code1](https://user-images.githubusercontent.com/38014237/66690216-e7cd1880-ec8e-11e9-8b83-a5d9fa7f4f50.png)
![theme_issue_code2](https://user-images.githubusercontent.com/38014237/66690217-e7cd1880-ec8e-11e9-9f22-2e435bc5f612.png)

In case an issue appears on the page, I noticed that two additional files are downloaded in the page code:
jquery.cropit.js
places.js

**Comment by harrison05** [comment] 2019-10-15 03:45
Hi @kerstar 

I check on some sites v4.7.8 but I can't reproduce this issue. Could you provide us your site and our team can check on it?

Regards.

**Comment by kerstar** [comment] 2019-10-15 22:22
Hi @harrison05 

Sure, I've given you the website address and login details in this ticket: #238280 

Remember to reproduce the issue as per my instructions.
I noticed the issue after disabling the google map module in the database - I set the activity to 0.
If you can, fix this bug please. Thanks.

Edit:
I still have this issue on the page: 
![theme_issue_1](https://user-images.githubusercontent.com/38014237/66874937-efe9c880-efac-11e9-89eb-a86946da51cd.png)

**Comment by harrison05** [comment] 2019-10-16 02:49
> I noticed the issue after disabling the google map module in the database - I set the activity to 0.

Which is this module? 
Please follow your ticket, our team will handle it.

Regards.

**Comment by kerstar** [comment] 2019-10-16 23:02
I have not expressed myself correctly. I meant the module in the table "phpfox_block". "Map View".
![theme_issue_2](https://user-images.githubusercontent.com/38014237/66965411-cd71b100-f079-11e9-80d0-0e12d3a88075.png)

Edit:
I re-enabled this module and then cleared the cache. This did not affect the removal of the issue The issue is still there.
The only difference between the fact when there is an issue and when it is not there are two additional files downloaded when the issue occurs:
jquery.cropit.js
places.js

**Comment by david-younet** [comment] 2019-11-13 06:12
Hi @kerstar ,

Thanks for your post, I have checked on your site, the issue caused is Follow suggestions block of Follow App have 2 </div> end of HTML file.
Please follow your ticket, we will reply and attachment the screen shoot for this issue.
We have fixed on your site, please check it.

Regards.

**Comment by david-phpFox** [comment] 2019-11-13 06:16
Hi @kerstar ,

Thanks for your post, I have checked on your site, the issue caused is Follow suggestions block of Follow App has 2 </div> end of HTML file.
Please follow your ticket, we will reply and attachment the screen shoot for this issue.
We have fixed on your site, please check it.

Regards.

**Comment by kerstar** [comment] 2019-11-13 23:20
Hi @david-phpFox 

Thank you for the information.
I checked and it looks like the bug has been fixed.
Thank you for helping me diagnose this problem and fix this issue! ;)
I thought it was a bug in phpfox, because the earlier version of phpfox with the Follow system app was not that issue. I will inform the developer about this bug.
Thank you again.

Regards.

**Closed as completed** 2019-11-20 02:32 UTC
Labels: Cannot reproduce
