### ISSUE TITLE
Incorrect chronological order in the Feed/User Feed

### ISSUE THREAD

**Issue by KamAZenok** [PHPfox-Official/phpfox-v4-issues#2422] opened 2018-11-07 11:43 UTC
# Important!

Please follow this template!

----------------------------------------

## What happened?
Incorrect chronological order in the Feed/User Feed

## Steps to reproduce:
Start to post news to the site.
(It cannot be reproduced every time, it happens randomly)

## What is expected?
After we have added a lot of records, we can see the following order from top to bottom (for example given only date and time of the news):
16 Sep. 18 21:40
16 Sep. 18 21:36
16 Sep. 18 21:33
16 Sep. 18 21:29
16 Sep. 18 21:26
---  Here we see the rotating circle, while the FEED loading previous data...  ---
... and again dublicates:
16 Sep. 18 21:40
16 Sep. 18 21:36

## Browsers and Devices tested
Chrome on Windows, Miscrosoft Edge on Windows, Firefox on Windows

## Server information
CentOS 7, php 5.6.37, MySQL 5.7.23, Apache

## phpFox version
phpFox 4.6.1 (build 6)

## Screenshots
![1](https://user-images.githubusercontent.com/44835622/48129646-2d24e100-e29b-11e8-8d64-6d64c49217ef.jpg)
![2](https://user-images.githubusercontent.com/44835622/48129653-34e48580-e29b-11e8-8cdb-118f01dd9fab.jpg)
![3](https://user-images.githubusercontent.com/44835622/48129660-3b72fd00-e29b-11e8-9ec2-7030c1358cd4.jpg)
![4](https://user-images.githubusercontent.com/44835622/48129664-3f9f1a80-e29b-11e8-9467-6a5fcba2d2a4.jpg)
![5](https://user-images.githubusercontent.com/44835622/48129674-4463ce80-e29b-11e8-9960-0720fc383d52.jpg)
![6](https://user-images.githubusercontent.com/44835622/48129691-4cbc0980-e29b-11e8-87b9-044bc5e4c828.jpg)
![7](https://user-images.githubusercontent.com/44835622/48129699-5180bd80-e29b-11e8-973b-71231054cad0.jpg)

**Comment by harrison05** [comment] 2018-11-09 02:36
Your issue seems like below topic: 
https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2370
And it was fixed on the newest version. Which phpFox version are you using? the newest version is 4.7.0

Regards.

**Comment by KamAZenok** [comment] 2018-11-09 17:21
Hello! I think it's not the same. That topic is speaking about doubles in profile photo and cover photo. But in my case I have doubles in photos simply uploaded in photo album.  Moreover, I have opened a ticket in the client area PhpFox about a month ago concerning this problem, and they didn't give a definite answer till now. I am still using phpFox 4.6.1 (build 6)

**Comment by harrison05** [comment] 2018-11-13 03:45
Your issue different with #2370 but I think they have the same root cause.

**Closed as completed** 2018-12-13 05:15 UTC
Labels: Fixed
