### ISSUE TITLE
Video Upload Issue

### ISSUE THREAD

**Issue by SalmanKhan86** [PHPfox-Official/phpfox-v4-issues#1872] opened 2017-02-05 08:19 UTC
when we upload video progress bar does't show status after some time.but when i check in notification window its says your video is ready.but in video tab its show nothing like video uploaded successfully.
after opening notification tab video is playing fine. 
test on 4.5.1 b2
![videoerror](https://cloud.githubusercontent.com/assets/13433124/22624705/f67d91e0-eba9-11e6-8e5f-fedb3de6d3fb.png)

**Comment by SalmanKhan86** [comment] 2017-02-05 11:32
and i have found following error in browser console after that notification comes see attachment 
![error](https://cloud.githubusercontent.com/assets/13433124/22625817/d810e80e-ebc4-11e6-9ffe-db80a38b287c.png)

**Comment by neil96** [comment] 2017-02-06 02:08
Hi @SalmanKhan86 ,

It's working on my side. Could you double check where is the JS error come from? It might be the root cause.

Regards.

**Comment by SalmanKhan86** [comment] 2017-02-06 05:02
what can i do for u

**Comment by SalmanKhan86** [comment] 2017-02-06 05:46
i am using Zencoder test account which allow me to show only 5 seconds of video is this problem related to Zencoder

**Comment by neil96** [comment] 2017-02-07 07:11
Hi @SalmanKhan86 

With Zencoder test account, the video will automatic cut down to 5 seconds. 

Regards.

**Comment by SalmanKhan86** [comment] 2017-02-07 07:13
i have submit a ticket in client area with my site info

**Comment by neil96** [comment] 2017-02-15 01:53
@SalmanKhan86 

Is your issue resolved via ticket?

Regards.

**Closed** 2017-03-03 02:19 UTC
Labels: Cannot reproduce
