### ISSUE TITLE
View 4 More Comments won't load on some Apps 

### ISSUE THREAD

**Issue by jimmybsilva** [PHPfox-Official/phpfox-v4-issues#2860] opened 2020-01-06 07:05 UTC
# Important

Please follow this template!

----------------------------------------

## What's happened?
When you click on the View 4 more comments it does not load the rest of the comments in the following apps

These are the only apps I have tried it on.

## Steps to reproduce:

When you click " View 4 more comments " nothing loads on the following app
The View 4 more disappears and shows you
When you click it only shows 4/8 (or  4/# of comments) but won't load the comments 

Not working
1. Videos
2. Events

expected?
When you click " View 4 more comments " it works and loads the comments that are missing

Works in the following 
1. Photos
2. Blog
3. Feed
## Browsers and Devices tested

PHP Version: | 7.2.26

...

## Server information

...

## phpFox version
Phpfox 4.7.9

...

## Screenshots
...

When you click it only shows 4/8 but won't load the comments 
![image](https://user-images.githubusercontent.com/35279981/71801330-7db6dc00-300f-11ea-8f35-ddbdb3bbf8bc.png)

**Comment by harrison05** [comment] 2020-01-10 03:08
Hi @jimmybsilva 

We can't reproduce this issue. Which version of Comments App you're using?
You can submit a ticket in client area, then our support team will help you figure out the cause.

Regards.

**Comment by jimmybsilva** [comment] 2020-01-13 16:56
This issue is even present in your demo site 

https://v4.phpfox.com/event/1/pizza-party/

![image](https://user-images.githubusercontent.com/35279981/72275292-7a5cbb00-35e2-11ea-881b-9945fc43a9a2.png)


It is supposed to show 6 comments not 4 only out of the 6 add another comment to it and you see that is missing comments

**Comment by jimmybsilva** [comment] 2020-01-13 16:58
I added another comment 

![image](https://user-images.githubusercontent.com/35279981/72275444-cad41880-35e2-11ea-99da-41b7e77a397b.png)

and still, it only shows 4 comments.

**Comment by jimmybsilva** [comment] 2020-01-13 16:59
phpfox APP 
This is the version
Comments | 4.1.2

**Comment by harrison05** [comment] 2020-01-14 08:22
Hi @jimmybsilva 

Ok, I got this issue. Our team will check and fix it.

Thanks.

**Comment by kerstar** [comment] 2020-02-06 20:21
Hi @harrison05 

Can you release update app for fix this issue?

**Comment by david-phpFox** [comment] 2020-03-23 03:40
This issue was fixed in Comments | 4.1.3

**Closed as completed by david-phpFox** 2020-03-23 03:40 UTC
Labels: Bug, Comments App
