### ISSUE TITLE
Mobile app - Deleted users (DU) in chat

### ISSUE THREAD

**Issue by sryn101** [PHPfox-Official/phpfox-v4-issues#2919] opened 2020-07-08 02:04 UTC
What's happened?
When someone deletes their profile, all other active users are seen as DU - Deleted User in chat, we have to go into their profile and get back to chat to see them as active. 

## Steps to reproduce:
1. Login with 3 different users and chat with each other using mobile app
2. Let one user delete his profile 
3. Go to back to Chat on mobile app, you will see other 2 users as DU - deleted user. 

## What's expected?
Active users shouldn't appear as deleted users. 

## Browsers and Devices tested
Android Mobiel app

...

## phpFox version
phpFox 4.8.0

...

## Screenshots
...

**Comment by harrison05** [comment] 2020-07-08 07:17
Hi @sryn101 

Which chat app you're using on your site? Instant Messaging or ChatPlus

Regards.

**Comment by sryn101** [comment] 2020-07-08 07:19
Hi Harrison, I am using Instant Messaging app.

**Comment by harrison05** [comment] 2020-07-09 03:05
Hi @sryn101 

We can't reproduce this issue on our side. It only shows Deleted User for friends who deleted their account.
![Screen Shot 2020-07-09 at 09 57 26](https://user-images.githubusercontent.com/41947198/86991984-a12f2f00-c1ca-11ea-8b6b-1cec7c7097f8.png)

On your side, what's happens if you click on the active users who showing as Deleted User? Can you chat with them? If you close and reopen app, this bug still happens or not?. Btw, you can submit a ticket in client area, our team will help you check it.

Regards.

**Comment by sryn101** [comment] 2020-07-09 03:23
On my end, if I click on active users, I can still chat with them, when I go to their profile from chat and come back to IM, I can see their name and profile pic. Similarly, I need to do for all users, only then I get to know who was actually "Deleted User" and who is active. Closing and reopening on app doesn't help. I will submit a ticket, thank you :)

**Comment by harrison05** [comment] 2020-07-13 09:32
I will close this topic now, please follow your ticket in client area. 
Let us know if you meet other issues with phpFox.

Thanks.

**Closed by harrison05** 2020-07-13 09:32 UTC
Labels: Cannot reproduce, Mobile App
