### ISSUE TITLE
Photo Privacy Messed Up

### ISSUE THREAD

**Issue by djafrika** [PHPfox-Official/phpfox-v4-issues#1717] opened 2016-10-29 10:29 UTC
Setting photo or album privacy to "friends only" results in friends not being able to see the photos. Only thumbnails in album.
Setting photo or album privacy to "Only Me" results in members being **able** to see the album and photo thumbnails. Only the feed info about that album is removed.

**Comment by bamafanz** [comment] 2016-10-29 13:59
Yes, 
We did the same thing with same result. Must change setting to Everyone to see the photos.
It leaves a blank page if set to Private..

**Comment by neil96** [comment] 2016-10-31 01:51
Could you put the name of that setting here.

**Comment by bamafanz** [comment] 2016-10-31 22:27
Sorry for late reply.  Once you create a photo album you can choose who views the photo.
Everyone, or just have it  Private to friends only. 
When its currently set on  Private to friends only , other users can still view their private pic.

**Comment by djafrika** [comment] 2016-11-03 08:40
name of that setting??

**Comment by neil96** [comment] 2016-11-03 08:44
>name of that setting??

Yes!

**Comment by djafrika** [comment] 2016-11-03 08:50
I don't understand... I've wrote everything. It's pretty clear what I'm talking about?

**Comment by phpfoxaccount** [comment] 2016-11-03 09:40
If it's a case, please follow our guideline at https://github.com/moxi9/phpfox we do need all related information in order to reproduce.

**Comment by djafrika** [comment] 2016-11-03 10:21
ignoring a problem doesn't solve it

**Comment by phpfoxaccount** [comment] 2016-11-03 10:42
@djafrika : this is a public github and we have policy clearly, please do follow. Otherwise we have to remove your post.

**Comment by bamafanz** [comment] 2016-11-09 13:51
Hello, 
This  is for the Privacy setting in  User groups - Registered user (Photos) 
please note where it says  :

Can use privacy settings when creating an album? This is set to YES..
This however is not currently functioning when enabled.

Members who are not friends with the user can still see the photos of the user. This also applies to the profile pics of the member,
The Privacy setting of Registered Users isnt working.

Trying not to cause conflict ,just wanted to report what we are seeing.

Thank you for your help 
![privacy settings user group registered user](https://cloud.githubusercontent.com/assets/18037526/20140530/4db2933c-a651-11e6-992b-8bbc2843ab69.PNG)

**Comment by bamafanz** [comment] 2016-11-09 14:35
This is a pic of a  Registered User looking at his Friends  photo album pic.
Notice the page is blank and no picture resides.
Both of these users are Friends.
![viewing friends photo album](https://cloud.githubusercontent.com/assets/18037526/20141761/6b671a50-a657-11e6-9e85-e4987eab7b11.PNG)

**Comment by one44123** [comment] 2016-11-25 03:12
Maybe the phpfox people must join the scriptechs forum as they seem to understand the issue clearly.

**Comment by Gatsby-PF** [comment] 2017-01-01 03:17
The permissions for photo items related to this post looks like it is happening in modules/photo/include/services/photo.class.php starting on line 552 through about 581.  Not sure what is happening not being a coder but maybe the tip will provide some focus.  The script appears to be associating the opposite permission with the photo/album being permissioned than what he user has set.

**Comment by one44123** [comment] 2017-01-19 15:51
Why has this not been addressed in release 4.5.1 this is a critical issue????

**Comment by PhpFoxJohnJr** [comment] 2017-03-29 03:52
I am very confused on this...it was labeled a bug on Nov 24, 2016 and this is something the users will noticed any you put a fix for 4.6 which I think you estimated June or July of 2017?  It is like you have over 100 bugs open?  Anything with privacy issues need to be fixed asap!  Not a year later!

**Comment by neil96** [comment] 2017-03-29 07:58
Hi all,

I have tested this issue again on v4.5.1 and v4.5.2 (will be released soon) but I can't not reproduce anymore. If you can reproduce on your site, please submit a ticket with your site information. 

Thanks!

**Comment by PhpFoxJohnJr** [comment] 2017-03-29 19:47
Neil, I have not tested it.  I was looking through your bug list (which to me seems low) and seeing if there is anything we need fixed now that the user would see as I really need a stable version that does not have bugs that the user will catch their first day on the site.  You guys have implement some great features now lets get a stable version.

**Closed** 2017-03-31 07:07 UTC
Labels: Cannot reproduce
