### ISSUE TITLE
Issue displaying month names in other languages

### ISSUE THREAD

**Issue by kerstar** [PHPfox-Official/phpfox-v4-issues#2591] opened 2019-03-03 21:53 UTC
## What's happened?
Hello,

I do not know why, but the translated phrase for the month March is badly displayed in phpfox. 
The translated phrase for the Polish language is "Marca" but "Marcaca" is displayed everywhere. 
It seems that the two letters "ca" are added to the translated phrase. Why is this happening? 
For the month of February there is no such issue. 
In the attachment I am sending screenshots where I showed this bug.

Can you help me fix this bug? It is very irritating...
I have provided data to my site in the ticket number: #655423

## Browsers and Devices tested
Chrome in Windows 10

## phpFox version
4.7.3

## Screenshots
![monthphrase1](https://user-images.githubusercontent.com/38014237/53702421-002aaa00-3e07-11e9-8a75-200d5692c7b2.png)
![monthphrase2](https://user-images.githubusercontent.com/38014237/53702422-002aaa00-3e07-11e9-99f9-f30b543aa16b.png)
![monthphrase3](https://user-images.githubusercontent.com/38014237/53702423-002aaa00-3e07-11e9-8a1f-7786636df506.png)

**Comment by harrison05** [comment] 2019-03-04 02:54
I can't reproduce your issue on my side.
![screen shot 2019-03-04 at 09 52 49](https://user-images.githubusercontent.com/41947198/53707862-5b8a8580-3e63-11e9-8a7d-509141a20a58.png)
Our team will check and support on your site via ticket

**Comment by david-phpFox** [comment] 2019-03-07 06:55
Fixed in Core 4.7.4

**Closed as completed by david-phpFox** 2019-03-07 06:55 UTC
Labels: Bug, Core
