### ISSUE TITLE
Too many issues! Look att eh lies https://www.phpfox.com/ 

### ISSUE THREAD

**Issue by VlogMe** [PHPfox-Official/phpfox-v4-issues#2374] opened 2018-08-27 05:03 UTC
Look at the lies! Look at the lies https://www.phpfox.com/ DON'T TAKE IT!

**Comment by spirogg** [comment] 2018-08-27 05:49
@VlogMe seems you cant spell #2373

> Too many issues! Look att eh lies

**Comment by Elshara** [comment] 2018-08-27 16:32
Works fine for me regarding most script functionality over here. Not
lying about that. Lol.

**Comment by harrison05** [comment] 2018-08-28 02:30
Duplicate of #2373

**Closed as completed by harrison05** 2018-08-28 02:30 UTC
Labels: Duplicate
