### ISSUE TITLE
groups profile pic not showing under members >> Joined Groups Block

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2345] opened 2018-08-07 07:03 UTC
----------------------------------------

## What happened?
... I added a group and added a profile pic, when I click on a member that joined that group on the left side of blocks it says joined groups, but the profile pic doesn't show see photo

## Steps to reproduce:
1. click a member that has joined a group look to left side blocks (joined Groups) see no profile pic showing, cleared cache and still nothing
2. 
3. 

## What is expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)
4.6.1.b5
...

## Screenshots
...
![joined groups no profile pic showing](https://user-images.githubusercontent.com/17736688/43759820-06164200-99e6-11e8-9619-7f5ae9bc5235.PNG)

**Comment by harrison05** [comment] 2018-08-08 03:06
Duplicate of #2338

**Closed as completed** 2018-08-08 03:07 UTC
Labels: Duplicate
