### ISSUE TITLE
Page Editor not loading

### ISSUE THREAD

**Issue by mrfenix** [PHPfox-Official/phpfox-v4-issues#1862] opened 2017-01-22 11:11 UTC
When trying to edit a page via the Admin panel the html editor does not show up and all divs on the page become invisible. This is the error I have in the console:

`13:05:18.110 SecurityError: Failed to load worker script at "http://cdn.jsdelivr.net/ace/1.1.8/min/worker-html.js" 1 (unknown)`

**Comment by neil96** [comment] 2017-01-23 01:57
Hi @mrfenix ,
I can't reproduce on my side. Btw, the file `http://cdn.jsdelivr.net/ace/1.1.8/min/worker-html.js` isn't default file. Could you double check this.
Regards.

**Comment by mrfenix** [comment] 2017-01-25 22:16
It appears to work when editing a page from the front end. But the backend editor is still broken.

**Comment by neil96** [comment] 2017-01-25 23:58
Hi @mrfenix ,

I checked in the backend. It works. Could you **double check the js file** `http://cdn.jsdelivr.net/ace/1.1.8/min/worker-html.js`, it isn't default file.

Regards.

**Closed** 2017-02-06 10:52 UTC
Labels: Cannot reproduce
