### ISSUE TITLE
User profile update issue

### ISSUE THREAD

**Issue by petati94** [PHPfox-Official/phpfox-v4-issues#2983] opened 2021-01-23 19:11 UTC
# Important

Please follow this template!

----------------------------------------

## What's happened?
The users cannot update their profiles when Birthday edit is disabled.

## Steps to reproduce:
1. Turn off "Can edit birthday?"
2. Try update a user profile.
3. 

## What's expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)
Phpfox 4.8.3
...

## Screenshots
...

**Comment by harrison05** [comment] 2021-01-25 02:53
Hi @petati94 

We will check and fix this bug.

Thanks for your report.

**Comment by harrison05** [comment] 2021-01-26 04:02
Hi @petati94 

Our development team said that they can't reproduce this issue on their side. You can try to logout and login back, then recheck it.

Regards.

**Comment by spirogg** [comment] 2021-01-26 07:50
@petati94 Update I got the error now as well.. 


 what exactly are you trying to update.. I tested on new installation 4.8.3 

1. I turned off can registered user can edit birthdate 
2. I then cleared cache and logged in as registered user.
3. the birthdate option (dropdown) does not show any more in profile. 
4. so I updated country state city zip code and currency 
5. then saved and no problem everything was updated and saved.

 - so are you trying to change something else in profile?
 -  when you say users can't update profile?
 - what did you try to update that is not working just wondering if you can be precise what exactly is not working. 
Spiro

**Comment by spirogg** [comment] 2021-03-08 05:25
@harrison05 

**yes this is a bug 4.8.3** 

- this setting needs to **turn off** : **Can edit date of birth?** in adminCP


- then I  clear cache and rebuilt core theme

- then I went in and logged in as a user and tried to add in user profile another zip code or add married etc. and a popup shows 
**The field `Date of Birth` is required.**

- screen shots to follow

**Comment by spirogg** [comment] 2021-03-08 05:36
@harrison05 

**ok here is screen shots** with ERROR

- 1st one is admincp setting : **turn off : Can edit date of birth?** 
- 
<img width="1440" alt="user-prfile" src="https://user-images.githubusercontent.com/17736688/110278926-d2504100-7f9d-11eb-9bb6-de8d3b2de60c.png">
- 2nd is sign in with registered user only and go to **update profile settings** 

<img width="1440" alt="admincp" src="https://user-images.githubusercontent.com/17736688/110278874-ba78bd00-7f9d-11eb-8da8-68f052569323.png">

- 3rd one is the actual **popup error** We receive 

<img width="1440" alt="error popup" src="https://user-images.githubusercontent.com/17736688/110278963-e1cf8a00-7f9d-11eb-8924-50861f4115db.png">

**Comment by harrison05** [comment] 2021-03-09 04:53
Hi @spirogg 

We can reproduce the issue with your steps. It will be fixed in the next version.

Regards.

**Comment by spirogg** [comment] 2021-03-09 04:57
@petati94 thank you for your initial report... sorry I did not understand 100% your report, but @harrison05 and team has marked as bug and will be fixed.. now they understand better how to reproduce.. :)

Spiro

**Closed as completed** 2021-04-13 01:53 UTC
Labels: Bug, Fixed, Core
