### ISSUE TITLE
SEO apps not open in iframe in admincp

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2195] opened 2018-03-09 03:28 UTC
## Steps to reproduce:
1. Admincp 
2. SEO 
3. Click links to.open SEO for modify meta description meta keywords. 

## What is expected
...
When you click on link to open description and keyword meta should.open in same windows of admincp .it's.opening new window.- new tab in browser. 
## Browsers tested
(Example: Chrome, Firefox and Microsoft Edge) latest chrome browser. 

## Server informations
...centos 7 cloudlinux 

## phpFox versions
... Fresh install 4.6.0

## Screenshots
...

**Comment by neil96** [comment] 2018-03-09 06:58
Duplicate of #2196

**Closed by neil96** 2018-03-09 06:58 UTC
