### ISSUE TITLE
Adding a smiley in CKeditor  in blog puts it on a line by itself.

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2759] opened 2019-08-27 00:33 UTC
## What happened?
When adding a smiley in a blog at the end of a sentence, it puts it in on a longe by itself.

## Steps to reproduce:
1.  Type in some sentence.
2. Add smilie icon
3. submit

## What is expected?
It should not put it on a line by itself.

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.7 (Upgraded), Material theme

...

## Screenshots
![Screenshot](https://user-images.githubusercontent.com/19594886/63732136-b87a5d80-c840-11e9-809e-53c7a8e41501.png)

**Comment by harrison05** [comment] 2019-08-27 03:29
I can't reproduce this issue on my side.
![Screen Shot 2019-08-27 at 10 28 07](https://user-images.githubusercontent.com/41947198/63738871-6fb0bc00-c8b5-11e9-8f9c-ea639a2b7161.png)

Please make sure your typing cursor doesn't in a newline when you select an emoji.

Regards.

**Comment by harrison05** [comment] 2019-08-27 03:32
Ok, emoji in CKEditor. I can see this issue. 
Our team will check and fix it.

Regards.

**Comment by david-phpFox** [comment] 2019-09-20 03:50
Fixed in Blog App 4.6.6

**Closed as completed by david-phpFox** 2019-09-20 03:50 UTC
Labels: Bug, Blog App
