### ISSUE TITLE
Same thing user3 liked your comment @user1 @user2 email funny links. 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2303] opened 2018-06-26 03:44 UTC
Also liked your comment  
----------------------------------------
Same as #2302
## What happened?
...
Edit:: moderator is staff. Admin is administrator and Maria is registered user 
Just FYI. 

Hello Moderator, 

Admin liked your comment "[user=1]Admin[/user] hi [user=3]Maria[/user] how ..." that you posted. 
To view this comment follow the link below: 
https://mysite.tld/comment/view/6/	

Kind Regards, 
- mysite.tld

Hello Moderator, 

Maria liked your comment "[user=1]Admin[/user] hi [user=3]Maria[/user] how ..." that you posted. 
To view this comment follow the link below: 
https://mysite.tld/comment/view/6/	

Kind Regards, 

## Steps to reproduce:
1. 
2. Same thing as liked status update 
3. 

## What is expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...

## Screenshots
...

**Comment by neil96** [comment] 2018-06-26 07:07
Duplicate of #2302

**Closed as completed by neil96** 2018-06-26 07:07 UTC
Labels: Duplicate
