### ISSUE TITLE
#hashtag

### ISSUE THREAD

**Issue by djafrika** [PHPfox-Official/phpfox-v4-issues#2566] opened 2019-01-23 13:00 UTC
What's happened?
I have set settings in admin panel to my liking for tags. I have enough tags to start trending. It did. I hit the #hashtag and it displays only one blog post with that tag... In DB I can see tags. Tags from different apps. So it's all good from that point. Why is it not displaying any other posts. Photo, forum, video, etc... The #hashtag is properly set in description of each app...

Steps to reproduce:
1. ad tags
2. recall tags
3. be disappointed

What's expected?
to work

Browsers and Devices tested
Chrome on Windows 10

Server information
CentOS 7, php 7.3 apache, nginx

phpFox version
4.7.2 (I have never had this working on any version)

It seems to be working on demo site, so before you put this request under cannot reproduce, note that other users on forum have same issue...

**Comment by harrison05** [comment] 2019-01-24 03:59
With the current version, filter by hashtag on feed have some limits. 
- It only shows items have that hashtag and their feed still exist. 
Example: you posted a blog with hashtag, it has feed and hashtag show on Trends > Click on it > Show feed of that blog. But when you delete feed > Click on hashtag again > Can't show that blog.
- With some apps support multiple uploads (Photo, Music), feed only supports filter by hashtag of **the First** item you uploaded.
Example: you upload 2 songs: A and B, song A upload first, then B and you hashtag on B > Can't search their feed by hashtag.

I know this is inconvenient. We should improve it in the future.
Regards.

**Comment by djafrika** [comment] 2019-01-24 11:40
So you do have plan fixing this? Nice...

**Comment by harrison05** [comment] 2019-01-25 03:28
Our team will check because it might need a big change on Feed to implement.

Thanks.

**Comment by djafrika** [comment] 2019-01-27 10:54
Couldn't it be done with simple code and cron job? 
I've tested it and found out that #hashtags are being stored in DB even if you edit the photo, video, blog, etc...
Even editing status update works!
So...

**Comment by harrison05** [comment] 2019-01-28 02:22
Yes, we saved hashtag in DB, so when you edit an item, it also updates hashtag. But when search hashtag on Feed, the search result is a Feed Item, not that Item. Therefore if feed is deleted, result can't be shown...

**Comment by djafrika** [comment] 2019-01-28 09:19
But when the feed item is **not deleted**, it's still **not shown**... That's why I posted this issue.
If I edit item and add #hashtag to it, it will not be displayed in news feed when searching for that #hashtag so it's pretty useless to have it. Hope that you'll fix this...

**Comment by harrison05** [comment] 2019-01-29 04:13
Which app occurs that issue on your site? I think it might a bug of some apps because I checked with Blog, Event and it's working well after edit and add new #hashtag.

**Comment by djafrika** [comment] 2019-01-29 08:21
Photo and video

**Comment by harrison05** [comment] 2019-01-30 02:45
Ok, I can reproduce with Video (We will check and fix), but Photo is still working well, here is my step: **Upload a photo > Save > Go to photo detail > Click Edit > Add a hashtag to description > Return to detail > Click on hashtag > It shows on feed.**
Note: As my previous comment, if you upload multiple photos, Feed can only search hashtag in the first photo.

**Comment by djafrika** [comment] 2019-01-30 09:18
Those are the same steps I was using... The only way to make it work is if I enter hashtag before posting...
eg. If I want to add a video, I do not post it on main feed, I must go to video, add new, paste url, and then add hashtags. This way the video does show up when clicking on hashtag. But this process is not intuitive for other users...

**Comment by harrison05** [comment] 2019-01-31 02:39
Why is this process not intuitive? Because users have to add a hashtag to video content if they want to filter video by it, also they can add hashtag when post video on feed, don't need to go to video.

**Comment by david-phpFox** [comment] 2019-03-06 06:50
Fixed on Videos 4.7.3

**Closed as completed by david-phpFox** 2019-03-06 06:50 UTC
Labels: Enhancement, Video App, Core
