### ISSUE TITLE
go to browse members and select a member the 120.png doesnt show 404 error 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2342] opened 2018-08-06 21:15 UTC
----------------------------------------

## What happened?
...
- go to browse members and select a member the 120.png doesnt show  when inspect with chrome browser it shows 404 error 

## Steps to reproduce:
1. go to browse member select a member 
2. see photo
3. 

## What is expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)
4.6.1.b5 
...

## Screenshots
...
![no profile pic showing here](https://user-images.githubusercontent.com/17736688/43741440-f42696aa-9993-11e8-9f9c-38debd3c00ba.PNG)

![capture](https://user-images.githubusercontent.com/17736688/43743127-356a93cc-999a-11e8-8301-5d6b9e25adf5.PNG)

![404 error](https://user-images.githubusercontent.com/17736688/43741447-f7634ff2-9993-11e8-8ea4-53c20365fb48.PNG)

**Comment by spirogg** [comment] 2018-08-06 21:16
#2338

**Comment by harrison05** [comment] 2018-08-07 02:50
Duplicate of #2338

**Closed as completed** 2018-08-07 03:12 UTC
Labels: Duplicate
