### ISSUE TITLE
Status backgrounds will cause user profile page to hang

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2757] opened 2019-08-25 19:15 UTC
## What happened?
Visiting a user's profile will sometimes cause the status background app to hang and the chrome browser will as you to terminate the page. After that it can be reloaded and works just fine.

## Steps to reproduce:
1. Visit a user's profile.
2. Click on the status entry box and try to enter a text. (it will sometime hang).
3. If it hangs, kill the page and then reload.

## What is expected?
It should not hang.

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.7 (Upgraded), Material theme

...

## Screenshots

...

**Comment by harrison05** [comment] 2019-08-26 03:17
It weird, I don't meet this issue. Does it only hang when typing on the status box with status background?

**Comment by prepperz** [comment] 2019-08-26 04:30
yes. When you click on the text box it will hang like the backgound app doesn't fully load.

**Comment by harrison05** [comment] 2019-08-27 03:09
I can't reproduce it. You can submit a ticket and our team will help to check on your site.

Regards.

**Comment by prepperz** [comment] 2019-08-27 06:16
Will do. This cannot be reproduced 100% of the time and only affects the profile page and nowhere else.

**Comment by harrison05** [comment] 2019-09-10 02:59
Ok. I will temporarily close this topic until you have any update about it.

Regards.

**Closed as completed by harrison05** 2019-09-10 02:59 UTC
Labels: Cannot reproduce
