### ISSUE TITLE
AGAIN After deleting the attachment it is not removed from the CDN server - phpFox 4.7.8

### ISSUE THREAD

**Issue by kerstar** [PHPfox-Official/phpfox-v4-issues#2804] opened 2019-10-10 23:34 UTC
Again, exactly the same bug, this time in phpfox 4.7.8.

I described the bug here: https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2733

Then you fixed it on my site (it was a bug in the \PF.Base\module\attachment\include\service\process.class.php file).

Now the structure of this file looks quite different and I can't apply that patch.

Why do you repeat these issues? 
Why don't you check phpfox before you release the next version? 
Why do I AGAIN await the release of ANOTHER version of phpfox that will fix a problem that has already been and which has already been repaired earlier? Why? For what sins? What the hell have I done that I always have to WAIT?

## phpFox version
PhpFox 4.7.8 (fresh installation), phpFox Storage app 4.6.3.

**Comment by harrison05** [comment] 2019-10-14 04:48
Did our team check your ticket in #2733 ? 
Did they confirm it is a bug or not? 
Normally, if we confirm a bug from tickets, we will fix it in our platform, besides that we update hotfix to customer site.

Regards.

**Comment by kerstar** [comment] 2019-10-14 23:28
@harrison05 
Of course I checked.
On github, this was not marked as an bug.

But look at this:
![attachments_issue3](https://user-images.githubusercontent.com/38014237/66788953-e5b2c600-eee9-11e9-90e9-53af1f1bb444.png)
![attachments_issue4](https://user-images.githubusercontent.com/38014237/66788954-e5b2c600-eee9-11e9-832d-46fafe6723d1.png)

The conversation concerns the ticket: #186715 

The change I noticed concerned the file:
\PF.Base\module\attachment\include\service\process.class.php

This code has been added to line 268 which has fixed the bug:
`Phpfox::getLib('cdn')->setServerId($aRow['server_id']);`

Everything worked fine, the bug was fixed and attachments were correctly removed from CDN servers.

However, I installed phpFox 4.7.8 for testing and migration purposes and this bug is still in phpFox 4.7.8!
So how did you fix it? In the ticket Hannah say that it was a bug and you fix it on my site, now you here say that there was no bug...

Improve communication in your team regarding issue reporting.
![attachments_issue](https://user-images.githubusercontent.com/38014237/66789233-0c253100-eeeb-11e9-9ecc-24147254d4b7.png)
![attachments_issue2](https://user-images.githubusercontent.com/38014237/66789235-0c253100-eeeb-11e9-9164-cfd9b3eff87f.png)

**Comment by harrison05** [comment] 2019-10-15 02:42
Ok, we confirm this is a bug of **phpFox Storage** and fixed it, not a bug of Core. 
Solution when we hotfix for you doesn't a best solution, so we removed it and fix again in phpFox Storage.
New version 4.6.4 of phpFox Storage had been released. 
Please upgrade this app on your site and check again (Attachment, Video...).

Regards.

**Comment by harrison05** [comment] 2019-10-15 02:47
I will close this topic. If the issue still occurs after upgrade v4.6.4, please inform us, I will reopen it.

Thanks.

**Closed as completed by harrison05** 2019-10-15 02:47 UTC
Labels: Bug, Fixed, phpFox Storage App
