### ISSUE TITLE
Green plus button bug  Can't upload videos, share music, photos add new page under user profile on Android htc 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2150] opened 2018-01-15 20:02 UTC
He when selection your user profile on Android phone running 7.1.1 HTC and selecting drop down menu to add photo video music tye green plus sign doesn't open tye option to share video share photo or share songs and even add new page doesn't work. 
Using.latest version 4.6.0 using material template. Tried with phpfox cdn on and off. Same issue.

**Comment by neil96** [comment] 2018-01-17 03:22
Hi @spirogg , could you give us more information.

Thanks!

**Comment by spirogg** [comment] 2018-01-17 04:37
@neil96 i select my page i created and i select the drop-down to try and add photos music etc etc, the green Plus button won't show me the share photo (popup) so i can upload a photo - Music - etc
See Photos
------------------------------------------------------------------------------------
![selecting-photo-music-anyone](https://user-images.githubusercontent.com/17736688/35025935-c3769cfa-fb0d-11e7-99fe-7dc8d0224678.png)

![green-plus-button-not-working](https://user-images.githubusercontent.com/17736688/35025954-d9177ab6-fb0d-11e7-92cd-3a59acf94c29.png)

![pages-try-to-upload-photo](https://user-images.githubusercontent.com/17736688/35025957-ddfd6d2e-fb0d-11e7-8c31-024d92bdf6a1.png)

**Comment by spirogg** [comment] 2018-01-17 04:39
this only happens on my cell phone, i dont get the little dropdown or popup whatever you want to call it, that says share photo (to upload a photo Via my cellphone?)

using windows 10 computer it works... 


thanks

Spiro

**Comment by spirogg** [comment] 2018-01-17 04:44
@neil96 this (Share Photos - doesn't show up on my cell phone when i click the green button

![share photos](https://user-images.githubusercontent.com/17736688/35026110-a6ef8a28-fb0e-11e7-8060-8afb06244809.jpg)

**Comment by spirogg** [comment] 2018-01-17 05:24
@neil96 when selecting the main menu to see all photos on site or all music on site the popup works to add photo and music, videos etc, 

![using main menu selecting music](https://user-images.githubusercontent.com/17736688/35027072-1fe6abe6-fb14-11e7-9428-b1a499659a49.png)

![selecting main menu photos](https://user-images.githubusercontent.com/17736688/35027085-3117f168-fb14-11e7-8e22-c7e22432bb67.png)



**@neil96 but when selecting from drop-down from groups pages your own profile it doesn't work**

**Comment by spirogg** [comment] 2018-01-17 05:28
@neil96 when selecting the main menu the Green + button doesn't move, it is on the bottom right as if it were floating and stays there as you scroll up or down, but on the other pages i show it moves when you scroll, so I think its got something to do with CSS or something in the placement of the button in the code

**Comment by spirogg** [comment] 2018-01-17 07:50
Sorry again in this post of I tagged you so much, from now on ill only tag you once in each post 👍

**Comment by neil96** [comment] 2018-01-18 10:29
Duplicate of #2157

**Closed by neil96** 2018-01-18 10:29 UTC
Labels: Duplicate
