### ISSUE TITLE
quiz SEO small fix see below

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2314] opened 2018-07-06 21:01 UTC
----------------------------------------

## What happened?
...

`<title>Quiz Meta Description</title><info>Meta description added to pages related to the Quizzes app. <a role="button" onclick="$Core.editMeta('seo_quiz_meta_description', true)">Click here</a> to edit meta description.<span style="float:right;">(SEO) <input style="width:150px;" readonly value="quiz_meta_description"></span></info>`

**- should be:** 

`<title>Quiz Meta Description</title><info>Meta description added to pages related to the Quizzes app. <a role="button" onclick="$Core.editMeta('seo_quiz_meta_description', true)">Click here</a> to edit meta description.<span style="float:right;">(SEO) <input style="width:150px;" readonly value="seo_quiz_meta_description"></span></info>`

and this one:

`<title>Quiz Meta Keywords</title><info>Meta keywords that will be displayed on sections related to the Quizzes app. <a role="button" onclick="$Core.editMeta('seo_quiz_meta_keywords', true)">Click here</a> to edit meta keywords.<span style="float:right;">(SEO) <input style="width:150px;" readonly value="quiz_meta_keywords"></span></info>`

**- should be:** 

`<title>Quiz Meta Keywords</title><info>Meta keywords that will be displayed on sections related to the Quizzes app. <a role="button" onclick="$Core.editMeta('seo_quiz_meta_keywords', true)">Click here</a> to edit meta keywords.<span style="float:right;">(SEO) <input style="width:150px;" readonly value="seo_quiz_meta_keywords"></span></info>
`

##small fix to unify all seo links the same 

thanks Spiro

## Steps to reproduce:
1. 
2. 
3. 

## What is expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...

## Screenshots
...

**Comment by neil96** [comment] 2018-07-09 02:27
Duplicate of #2315

**Closed as completed by neil96** 2018-07-09 02:27 UTC
Labels: Duplicate
