### ISSUE TITLE
Activity points history. Gifting points today is not displayed in sent history unless the "to" date is set into the future

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2517] opened 2018-12-28 03:48 UTC
## What happened?
Gifting points today is not displayed in sent history unless the "to" date is set into the future

## Steps to reproduce:
1. show activity point for today and it will not show what you gifted.
2. Set the "to"  date for tomorrow and it shows what you gifted today.
3. 

## What is expected?
...

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.1 (Upgraded), Material theme

...

## Screenshots

**Comment by harrison05** [comment] 2019-01-02 04:19
Can't reproduce your issue in my side, see my screenshot
![screen shot 2019-01-02 at 11 18 19](https://user-images.githubusercontent.com/41947198/50580358-3340d380-0e80-11e9-86eb-4954565b393e.png)

**Comment by harrison05** [comment] 2019-01-02 04:20
![screen shot 2019-01-02 at 11 20 18](https://user-images.githubusercontent.com/41947198/50580378-67b48f80-0e80-11e9-83d3-695db9f231e5.png)

**Comment by prepperz** [comment] 2019-01-02 05:06
@harrison05  I'm using activity points 4.7.4. Which version are you testing?

**Comment by prepperz** [comment] 2019-01-02 05:36
So, I'm noticing something weird.
![screenshot](https://user-images.githubusercontent.com/19594886/50581296-6d7d8700-0e26-11e9-9255-1c8a9a70bdc5.png)

**Comment by harrison05** [comment] 2019-01-03 08:51
Yes, I saw your screenshot and reproduce it, a bug of this App or Core. 
We will check and fix it.

Thanks.

**Comment by david-phpFox** [comment] 2019-04-16 08:52
Fixed in Activity Points 4.7.5

**Closed as completed by david-phpFox** 2019-04-16 08:52 UTC
Labels: Bug, Fixed, Activity Point App
