### ISSUE TITLE
Phrase in ad app / music sponsor setting needs correction / also settings are not relevant to selected apps

### ISSUE THREAD

**Issue by hamadax** [PHPfox-Official/phpfox-v4-issues#2752] opened 2019-08-20 05:09 UTC
# Important

Please follow this template!

----------------------------------------

## What's happened?
Go to: /admincp/ad/sponsor-setting/?module_id=music&group_id=2

Incorrect phrase: Can members of this user group mark a song as Sponsor?
Correct phrase: Can members of this user group mark a song as Sponsor **without paying  fee**?

## Steps to reproduce:
1. See above
2. 
3. 

## What's expected?
Fix the phrase please and organize the settings for each app properly.

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

Latest as of 8/20/19

## Screenshots
...
![image](https://user-images.githubusercontent.com/48427415/63319110-f62e3200-c2e6-11e9-9664-804da0066db9.png)

**Comment by hamadax** [comment] 2019-08-20 05:13
In addition, when selecting a specific Groups / Apps filter on top, some options appear that do not make sense for the selected combination. Example below is a mixture between music and photo albums showing in the same screen when only music is selected for registered users... photo albums are from the photo app:

![image](https://user-images.githubusercontent.com/48427415/63319284-8a989480-c2e7-11e9-9d21-3df251fbc0f0.png)

**Comment by harrison05** [comment] 2019-08-21 03:14
> Incorrect phrase: Can members of this user group mark a song as Sponsor?
> Correct phrase: Can members of this user group mark a song as Sponsor without paying fee?

We will check this.

> In addition, when selecting a specific Groups / Apps filter on top, some options appear that do not make sense for the selected combination. Example below is a mixture between music and photo albums showing in the same screen when only music is selected for registered users... photo albums are from the photo app:

You're using v4.6.0, and this issue occurs because of conflict phrases between Music and Photo app. Which version of those apps you are using? Because it doesn't show with the latest versions.

**Comment by hamadax** [comment] 2019-08-21 03:20
Music: 4.6.4
Photos: 4.7.6

**Comment by harrison05** [comment] 2019-08-22 02:43
Our development team checked and confirmed that issue occurs because conflict setting phrases name between Music and Photo app. We will check and fix it.

Regards.

**Comment by david-phpFox** [comment] 2019-09-25 02:16
Fixed in Photos App 4.7.7.

**Closed as completed by david-phpFox** 2019-09-25 02:16 UTC
Labels: Bug, Photos App
