### ISSUE TITLE
Need to check Transaction History page on Activity Points App.

### ISSUE THREAD

**Issue by PhpFoxJohnJr** [PHPfox-Official/phpfox-v4-issues#2859] opened 2020-01-01 07:42 UTC
Sorry, but I just did a fresh install (stopped working on the project three upgrades ago as I figure 4.7.9 would be the final before big changes and most bugs would be fixed)
Anyways, finding lots of bugs in 3rd apps so I will be brief for the phpfox issue I just found.

**This was tested on the phpfox demo site.**

You need to review the entire page for Transaction History for the Activity Points App.  

 First, the calendar only shows 2020 and 2021 year when transactions occurred in 2019

Second, type in the member field admin and filter and no transaction show.

Third, the action type field does not match was is listed below.

Fourth, the Type field does not show results for received points...not sure if it is the member field issue.

Fifth, when you hit the reset button all transaction does not show up...need to click on the transaction tab again.

Sixth, an example in Module/App field, the default "All" is in the beginning but if you pick an app then "All" is not in the list so you must go back to the top and click transaction history again and start over.

Seventh, in my App column I have a transaction where the App is Subscribe (person used activity points to buy a subscription).  I don't see the filter option anywhere.

Eighth, not really a bug but confusing.  You use Type in the filter and that I guess is the column for Point Source.  Maybe the bottom should be Type as well as it is a shorter word as well.  Monitor or phone screen space is a valuable space to be wasting on long words.  Like the App column that repeats "Activity Points" instead of Act Pts or AP.  Just saying I would rather see an extra column of maybe city/state or location column instead of long words.  You know how many Dave Smith's are in the United States.  I have to click on each one to find out if it was the right Dave Smith in Chicago.  Another example...column title Member ID.  Why not User ID?  Just saying...Member ID uses 9 character spaces.  To match those character spaces in users the Member ID would have to be 999999999.  That is one user id less than a billion users sign up.  Not trying to be a pain...just want you to think more like a user than a coder.

I don't know who worked on this but this is not GOOD.  I took a total of 28 minutes to find all these bugs....NOT GOOD for 4.7.9

Somone need to go through this and think on how we are going to use this for a 100 member to 50,000 members.

Things to remember when fixing all these issues:
We should be able to search members by the last name only as well as first and last.
We should be able to search by one field with the name empty.
The default "To Date" should be the current date automatically but able to change to previous dates if needed
Don't see any filter for gifted points that shows up in my action column.
Member's name column should be able to sort as well.
Date column needs to abbreviate (Current: February 22, 2019 should be 02/22/2019) 
The transaction history should be exportable too .CSV as well.
Maybe a column of Total Pts AT (AT = After Transaction) to help with solving point issues.

OK, I gave you 30 minutes of my time for free....good luck :)
Some of these may not be bugs but I could not get them to work so I am assuming.

![Activity-Point-Calendar-Issue](https://user-images.githubusercontent.com/14913734/71639176-72db0080-2c37-11ea-8a41-f44c2066563a.jpg)

**Comment by harrison05** [comment] 2020-01-02 03:12
Hi @PhpFoxJohnJr 

Thanks for your report. 
We checked all the points. 

- Following points we will fix in the future: 

> First, the calendar only shows 2020 and 2021 year when transactions occurred in 2019
> Fifth, when you hit the reset button all transaction does not show up...need to click on the transaction tab again.

- Point Eighth, we will check some cases at this point:
> You use Type in the filter and that I guess is the column for Point Source. Maybe the bottom should be Type as well as it is a shorter word as well...
> ...Another example...column title Member ID. Why not User ID? Just saying...Member ID uses 9 character spaces...

- Following points we can't reproduce, it's working well as design (please make sure date range you filter has transactions):
> Second, type in the member field admin and filter and no transaction show.
> Third, the action type field does not match was is listed below.
> Fourth, the Type field does not show results for received points...not sure if it is the member field issue.

![Screen Shot 2020-01-02 at 10 10 42](https://user-images.githubusercontent.com/41947198/71650417-47940680-2d48-11ea-8624-68dcfef7c0a3.png)


- Point Sixth: you can reset the value of this dropdown to "All" by click on it and delete text on it.
- Point Seventh: we will check, if this is a bug, we will fix it.

Regards.

**Comment by PhpFoxJohnJr** [comment] 2020-01-02 03:24
Thanks, didn't know a date was required.  Should a date be required?  I would think you should be able to pick any field and it would filter it.  Even the "from date" should be date site opened and the "to date" field as the default for the "to date" field should be the current date.

**Comment by harrison05** [comment] 2020-12-11 02:28
Fixed on Activity Points v4.7.7

**Closed as completed** 2020-12-11 02:28 UTC
Labels: Bug, Fixed, Activity Point App
