### ISSUE TITLE
I've raised this issue before. See: https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/768

### ISSUE THREAD

**Issue by hamadax** [PHPfox-Official/phpfox-v4-issues#2662] opened 2019-05-13 14:05 UTC
I've raised this issue before. See: https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/768

_Originally posted by @prepperz in https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2660#issuecomment-490809641_

See my update with videos!

https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2660#issuecomment-491827728

**Comment by harrison05** [comment] 2019-05-16 03:09
Duplicate of #2660

**Closed as completed by harrison05** 2019-05-16 03:09 UTC
