### ISSUE TITLE
Pages video thumbnail not aligned when scrolling down

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2464] opened 2018-12-08 09:14 UTC
![screenshot](https://user-images.githubusercontent.com/19594886/49684291-1ba04600-faa0-11e8-963d-b8df1b59b94a.png)

**Comment by harrison05** [comment] 2018-12-12 03:31
It might have the same root cause with issue #2429

**Comment by prepperz** [comment] 2018-12-13 04:50
Groups are also affected

**Comment by david-phpFox** [comment] 2018-12-13 04:59
Fixed on Pages 4.7.0 and Groups 4.7.0

**Closed as completed by david-phpFox** 2018-12-13 04:59 UTC
Labels: Bug, Fixed, Groups App, Pages App

**Comment by prepperz** [comment] 2018-12-13 14:35
Still not fixed in pages or groups for 4.7
